name: Deploy Polaris Gateway

on:
  push:
    branches:
      - main
      - develop

env:
  IMAGE_NAME: lucassuntech/polaris-gateway

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Determine Docker tag (short SHA)
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login no Docker Hub
        run: |
          echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" \
            | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker images
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            IMAGE="${IMAGE_NAME}:${TAG}"
            docker build -t $IMAGE .
            docker tag $IMAGE $IMAGE_NAME:latest
            docker push "$IMAGE"
            docker push "$IMAGE_NAME:latest"
          else
            IMAGE="${IMAGE_NAME}:develop-${TAG}"
            docker build -t $IMAGE .
            docker tag $IMAGE $IMAGE_NAME:develop
            docker push "$IMAGE"
            docker push "$IMAGE_NAME:develop"
          fi

  deploy-to-k8s:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & rollout restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export KUBECONFIG=/home/devops/.kube/config

            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              NAMESPACE=bff-prod
              DEPLOYMENT=aurora-bff
              IMAGE_TAG=latest
            else
              NAMESPACE=homolog
              DEPLOYMENT=gateway-homolog
              IMAGE_TAG=develop
            fi

            echo "Restarting $DEPLOYMENT in namespace $NAMESPACE to pull :$IMAGE_TAG…"

            # reinicia o rollout, puxando a imagem apropriada
            kubectl rollout restart deployment/${DEPLOYMENT} -n ${NAMESPACE}

            # aguarda a nova versão entrar em Ready
            kubectl rollout status deployment/${DEPLOYMENT} \
              -n ${NAMESPACE} \
              --timeout=120s
